# Generated by Django 3.2.18 on 2023-05-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sowstat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='area',
            new_name='area_of_land',
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
