# Generated by Django 3.2.18 on 2023-05-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sowstat', '0002_auto_20230505_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='area_of_land',
            new_name='area',
        ),
    ]
